library(Rcpp)
Rcpp::sourceCpp("jaccard.cpp")
args <- commandArgs(trailingOnly = TRUE)
v <- function(...) cat(sprintf(...), sep='', file=stderr())
dff <- read.csv(args[1],header=TRUE,row.names=1,sep='\t',check.names=FALSE)
a<-as.vector(dff[,1])
b<-as.vector(dff[,2])
c<-as.vector(dff[,3])
d<-as.vector(dff[,4])
j1 <- JaccardIndex(a,a)
j2 <- JaccardIndex(a,b)
j3 <- JaccardIndex(a,c)
j4 <- JaccardIndex(a,d)
v("%f,%f,%f,%f\n", j1, j2, j3, j4)
